export const worldCapitals = [
    { capital: "Kabul", country: "Afghanistan" },
    { capital: "Tirana", country: "Albania" },
    { capital: "Algiers", country: "Algeria" },
    { capital: "Andorra la Vella", country: "Andorra" },
    { capital: "Luanda", country: "Angola" },
    { capital: "Saint John's", country: "Antigua and Barbuda" },
    { capital: "Buenos Aires", country: "Argentina" },
    { capital: "Yerevan", country: "Armenia" },
    { capital: "Canberra", country: "Australia" },
    { capital: "Vienna", country: "Austria" },
    { capital: "Baku", country: "Azerbaijan" },
    { capital: "Nassau", country: "Bahamas" },
    { capital: "Manama", country: "Bahrain" },
    { capital: "Dhaka", country: "Bangladesh" },
    { capital: "Bridgetown", country: "Barbados" },
    { capital: "Minsk", country: "Belarus" },
    { capital: "Brussels", country: "Belgium" },
    { capital: "Belmopan", country: "Belize" },
    { capital: "Porto-Novo", country: "Benin" },
    { capital: "Thimphu", country: "Bhutan" },
    { capital: "Sucre", country: "Bolivia" },
    { capital: "Sarajevo", country: "Bosnia and Herzegovina" },
    { capital: "Gaborone", country: "Botswana" },
    { capital: "Brasília", country: "Brazil" },
    { capital: "Bandar Seri Begawan", country: "Brunei" },
    { capital: "Sofia", country: "Bulgaria" },
    { capital: "Ouagadougou", country: "Burkina Faso" },
    { capital: "Gitega", country: "Burundi" },
    { capital: "Praia", country: "Cabo Verde" },
    { capital: "Phnom Penh", country: "Cambodia" },
    { capital: "Yaoundé", country: "Cameroon" },
    { capital: "Ottawa", country: "Canada" },
    { capital: "Bangui", country: "Central African Republic" },
    { capital: "N'Djamena", country: "Chad" },
    { capital: "Santiago", country: "Chile" },
    { capital: "Beijing", country: "China" },
    { capital: "Bogotá", country: "Colombia" },
    { capital: "Moroni", country: "Comoros" },
    { capital: "Brazzaville", country: "Congo" },
    { capital: "San José", country: "Costa Rica" },
    { capital: "Zagreb", country: "Croatia" },
    { capital: "Havana", country: "Cuba" },
    { capital: "Nicosia", country: "Cyprus" },
    { capital: "Prague", country: "Czechia" },
    { capital: "Copenhagen", country: "Denmark" },
    { capital: "Djibouti", country: "Djibouti" },
    { capital: "Roseau", country: "Dominica" },
    { capital: "Santo Domingo", country: "Dominican Republic" },
    { capital: "Quito", country: "Ecuador" },
    { capital: "Cairo", country: "Egypt" },
    { capital: "San Salvador", country: "El Salvador" },
    { capital: "Malabo", country: "Equatorial Guinea" },
    { capital: "Asmara", country: "Eritrea" },
    { capital: "Tallinn", country: "Estonia" },
    { capital: "Eswatini", country: "Mbabane" },
    { capital: "Addis Ababa", country: "Ethiopia" },
    { capital: "Suva", country: "Fiji" },
    { capital: "Helsinki", country: "Finland" },
    { capital: "Paris", country: "France" },
    { capital: "Libreville", country: "Gabon" },
    { capital: "Banjul", country: "Gambia" },
    { capital: "Tbilisi", country: "Georgia" },
    { capital: "Berlin", country: "Germany" },
    { capital: "Accra", country: "Ghana" },
    { capital: "Athens", country: "Greece" },
    { capital: "Saint George's", country: "Grenada" },
    { capital: "Guatemala City", country: "Guatemala" },
    { capital: "Conakry", country: "Guinea" },
    { capital: "Bissau", country: "Guinea-Bissau" },
    { capital: "Georgetown", country: "Guyana" },
    { capital: "Port-au-Prince", country: "Haiti" },
    { capital: "Tegucigalpa", country: "Honduras" },
    { capital: "Budapest", country: "Hungary" },
    { capital: "Reykjavik", country: "Iceland" },
    { capital: "New Delhi", country: "India" },
    { capital: "Jakarta", country: "Indonesia" },
    { capital: "Tehran", country: "Iran" },
    { capital: "Baghdad", country: "Iraq" },
    { capital: "Dublin", country: "Ireland" },
    { capital: "Jerusalem", country: "Israel" },
    { capital: "Rome", country: "Italy" },
    { capital: "Kingston", country: "Jamaica" },
    { capital: "Tokyo", country: "Japan" },
    { capital: "Amman", country: "Jordan" },
    { capital: "Nur-Sultan", country: "Kazakhstan" },
    { capital: "Nairobi", country: "Kenya" },
    { capital: "Tarawa", country: "Kiribati" },
    { capital: "Pyongyang", country: "North Korea" },
    { capital: "Seoul", country: "South Korea" },
    { capital: "Kuwait City", country: "Kuwait" },
    { capital: "Bishkek", country: "Kyrgyzstan" },
    { capital: "Vientiane", country: "Laos" },
    { capital: "Riga", country: "Latvia" },
    { capital: "Beirut", country: "Lebanon" },
    { capital: "Maseru", country: "Lesotho" },
    { capital: "Monrovia", country: "Liberia" },
    { capital: "Tripoli", country: "Libya" },
    { capital: "Vaduz", country: "Liechtenstein" },
    { capital: "Vilnius", country: "Lithuania" },
    { capital: "Luxembourg", country: "Luxembourg" },
    { capital: "Antananarivo", country: "Madagascar" },
    { capital: "Lilongwe", country: "Malawi" },
    { capital: "Kuala Lumpur", country: "Malaysia" },
    { capital: "Male", country: "Maldives" },
    { capital: "Bamako", country: "Mali" },
    { capital: "Valletta", country: "Malta" },
    { capital: "Majuro", country: "Marshall Islands" },
    { capital: "Nouakchott", country: "Mauritania" },
    { capital: "Port Louis", country: "Mauritius" },
    { capital: "Mexico City", country: "Mexico" },
    { capital: "Chisinau", country: "Moldova" },
    { capital: "Monaco", country: "Monaco" },
    { capital: "Ulaanbaatar", country: "Mongolia" },
    { capital: "Podgorica", country: "Montenegro" },
    { capital: "Rabat", country: "Morocco" },
    { capital: "Maputo", country: "Mozambique" },
    { capital: "Naypyidaw", country: "Myanmar" },
    { capital: "Windhoek", country: "Namibia" },
    { capital: "Yaren", country: "Nauru" },
    { capital: "Kathmandu", country: "Nepal" },
    { capital: "Amsterdam", country: "Netherlands" },
    { capital: "Wellington", country: "New Zealand" },
    { capital: "Managua", country: "Nicaragua" },
    { capital: "Niamey", country: "Niger" },
    { capital: "Abuja", country: "Nigeria" },
    { capital: "Skopje", country: "North Macedonia" },
    { capital: "Oslo", country: "Norway" },
    { capital: "Muscat", country: "Oman" },
    { capital: "Islamabad", country: "Pakistan" },
    { capital: "Ngerulmud", country: "Palau" },
    { capital: "Panama City", country: "Panama" },
    { capital: "Port Moresby", country: "Papua New Guinea" },
    { capital: "Asunción", country: "Paraguay" },
    { capital: "Lima", country: "Peru" },
    { capital: "Manila", country: "Philippines" },
    { capital: "Warsaw", country: "Poland" },
    { capital: "Lisbon", country: "Portugal" },
    { capital: "Doha", country: "Qatar" },
    { capital: "Bucharest", country: "Romania" },
    { capital: "Moscow", country: "Russia" },
    { capital: "Kigali", country: "Rwanda" },
    { capital: "Basseterre", country: "Saint Kitts and Nevis" },
    { capital: "Castries", country: "Saint Lucia" },
    { capital: "Kingstown", country: "Saint Vincent and the Grenadines" },
    { capital: "Apia", country: "Samoa" },
    { capital: "San Marino", country: "San Marino" },
    { capital: "São Tomé", country: "São Tomé and Príncipe" },
    { capital: "Riyadh", country: "Saudi Arabia" },
    { capital: "Dakar", country: "Senegal" },
    { capital: "Belgrade", country: "Serbia" },
    { capital: "Victoria", country: "Seychelles" },
    { capital: "Freetown", country: "Sierra Leone" },
    { capital: "Singapore", country: "Singapore" },
    { capital: "Bratislava", country: "Slovakia" },
    { capital: "Ljubljana", country: "Slovenia" },
    { capital: "Honiara", country: "Solomon Islands" },
    { capital: "Mogadishu", country: "Somalia" },
    { capital: "Pretoria", country: "South Africa" },
    { capital: "Juba", country: "South Sudan" },
    { capital: "Madrid", country: "Spain" },
    { capital: "Colombo", country: "Sri Lanka" },
    { capital: "Khartoum", country: "Sudan" },
    { capital: "Paramaribo", country: "Suriname" },
    { capital: "Stockholm", country: "Sweden" },
    { capital: "Bern", country: "Switzerland" },
    { capital: "Damascus", country: "Syria" },
    { capital: "Taipei", country: "Taiwan" },
    { capital: "Dushanbe", country: "Tajikistan" },
    { capital: "Dodoma", country: "Tanzania" },
    { capital: "Bangkok", country: "Thailand" },
    { capital: "Lomé", country: "Togo" },
    { capital: "Nukuʻalofa", country: "Tonga" },
    { capital: "Port of Spain", country: "Trinidad and Tobago" },
    { capital: "Tunis", country: "Tunisia" },
    { capital: "Ankara", country: "Turkey" },
    { capital: "Ashgabat", country: "Turkmenistan" },
    { capital: "Funafuti", country: "Tuvalu" },
    { capital: "Kampala", country: "Uganda" },
    { capital: "Kyiv", country: "Ukraine" },
    { capital: "Abu Dhabi", country: "United Arab Emirates" },
    { capital: "London", country: "United Kingdom" },
    { capital: "Washington, D.C.", country: "United States" },
    { capital: "Montevideo", country: "Uruguay" },
    { capital: "Tashkent", country: "Uzbekistan" },
    { capital: "Port Vila", country: "Vanuatu" },
    { capital: "Caracas", country: "Venezuela" },
    { capital: "Hanoi", country: "Vietnam" },
    { capital: "Sana'a", country: "Yemen" },
    { capital: "Lusaka", country: "Zambia" },
    { capital: "Harare", country: "Zimbabwe" },
    { capital: "Kinshasa", country: "Democratic Republic of the Congo" },
    { capital: "Yamoussoukro", country: "Côte d'Ivoire" },
    { capital: "Dili", country: "Timor-Leste" },
    { capital: "Palikir", country: "Federated States of Micronesia" },
    { capital: "Vatican City", country: "Vatican City" },
];